### ISSUE TITLE
java.lang.NoClassDefFoundError: org/fintrace/core/drivers/tspl/commands/TSPLCommand

### ISSUE THREAD

**Issue by hoangtu92** [fintrace/tspl2-driver#14]
Hello, here is my main class. I can build the package but when I run I got the error. thanks

package com.mycompany.app;

import org.fintrace.core.drivers.tspl.commands.device.Counter;
import org.fintrace.core.drivers.tspl.commands.device.CounterExpression;
import org.fintrace.core.drivers.tspl.commands.label.BarcodeAlignment;
import org.fintrace.core.drivers.tspl.commands.label.BarcodeRotation;
import org.fintrace.core.drivers.tspl.commands.label.DataMatrix;
import org.fintrace.core.drivers.tspl.commands.label.Text;
import org.fintrace.core.drivers.tspl.commands.label.TscLabel;
import org.fintrace.core.drivers.tspl.commands.system.ClearBuffer;
import org.fintrace.core.drivers.tspl.commands.system.Direction;
import org.fintrace.core.drivers.tspl.commands.system.Gap;
import org.fintrace.core.drivers.tspl.commands.system.Print;
import org.fintrace.core.drivers.tspl.commands.system.Size;

public class App 
{
    public static void main( String[] args )
    {
        // USB Client
        //TSPLConnectionClient tsplConnectionClient = new USBConnectionClient(
                //(short) Integer.parseInt(properties().getProperty("tsc.vendor.id"), 16),
                //(short) Integer.parseInt(properties().getProperty("tsc.product.id"), 16));

        //tsplConnectionClient.init();

        //tsplConnectionClient.connect();

        TscLabel tscLabel = TscLabel.builder()
                .element(Size.builder().labelWidth(4f).labelLength(3f).build())
                .element(Gap.builder().labelDistance(0f).labelOffsetDistance(0f).build())
                .element(Direction.builder().printPositionAsFeed(Boolean.TRUE).build())
                .element(ClearBuffer.builder().build())
                .element(DataMatrix.builder().xCoordinate(10).yCoordinate(110).width(400)
                        .height(400).content("DMATRIX EXAMPLE 1").build())
                .element(DataMatrix.builder().xCoordinate(310).yCoordinate(110).width(400)
                        .height(400).moduleSize(6).content("DMATRIX EXAMPLE 2").build())
                .element(DataMatrix.builder().xCoordinate(10).yCoordinate(310).width(400)
                        .height(400).moduleSize(8).nbRows(18).nbCols(18)
                        .content("DMATRIX EXAMPLE 3").build())
                .element(Print.builder().nbLabels(1).nbCopies(1).build())
                .build();

        System.out.println(tscLabel);

        //tsplConnectionClient.send(tscLabel);

        //tsplConnectionClient.disconnect();
        //tsplConnectionClient.shutdown();
    }
}

**Comment by koneru9999** [comment]
Hi @hoangtu92 ,

I am not sure how you have compiled the code. 

Instead of compiling, this library is also available on mvn central repository.

```xml
<!-- https://mvnrepository.com/artifact/org.fintrace.core.drivers/tspl2-driver -->
<dependency>
    <groupId>org.fintrace.core.drivers</groupId>
    <artifactId>tspl2-driver</artifactId>
    <version>0.0.7</version>
</dependency>
```

**Comment by hoangtu92** [comment]
Thank you for replying that fast. I added to my pom.xml already. But I cannot run the jar after build the package.

**Comment by koneru9999** [comment]
Could you please check if the jar has been downloaded properly (repository folder of your local .m2 folder)? if in doubt, Remove the existing jar and let the maven download again.

I have verified just now by downloading the jar from mvn central, and the TSPLCommand does exists in the jar.

**Comment by hoangtu92** [comment]
Here I attached the screenshot.
https://imgur.com/a/Fz5I9qA

it does exists in the directory but I still got the error. here
https://imgur.com/a/0fiPCSn

**Comment by hoangtu92** [comment]
Hi. Sorry. I foundout that my jar does not contain dependencies. Thank you so much for your help.

**Comment by hoangtu92** [comment]
for anyone have similar issue like me, which I doubt there is. But still here is what I do:

- added this to pom.xml, replace `fully.qualified.MainClass` with the main class

`<build>
  <plugins>
    <plugin>
      <artifactId>maven-assembly-plugin</artifactId>
      <configuration>
        <archive>
          <manifest>
            <mainClass>fully.qualified.MainClass</mainClass>
          </manifest>
        </archive>
        <descriptorRefs>
          <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
      </configuration>
    </plugin>
  </plugins>
</build>`
 

and `run mvn clean compile assembly:single`

this is very basic knowledge @@
