### ISSUE TITLE
Error:(39, 42) java: cannot find symbol   symbol:   method properties()

### ISSUE THREAD

**Issue by hoangtu92** [fintrace/tspl2-driver#15]
Hello, I cannot find where is this function come from:

properties().getProperty("tsc.vendor.id")

please help, thanks

`package com.mycompany.app;

import org.fintrace.core.drivers.tspl.commands.device.Counter;
import org.fintrace.core.drivers.tspl.commands.device.CounterExpression;
import org.fintrace.core.drivers.tspl.commands.label.BarcodeAlignment;
import org.fintrace.core.drivers.tspl.commands.label.BarcodeRotation;
import org.fintrace.core.drivers.tspl.commands.label.DataMatrix;
import org.fintrace.core.drivers.tspl.commands.label.Text;
import org.fintrace.core.drivers.tspl.commands.label.TscLabel;
import org.fintrace.core.drivers.tspl.commands.system.ClearBuffer;
import org.fintrace.core.drivers.tspl.commands.system.Direction;
import org.fintrace.core.drivers.tspl.commands.system.Gap;
import org.fintrace.core.drivers.tspl.commands.system.Print;
import org.fintrace.core.drivers.tspl.commands.system.Size;

import lombok.extern.slf4j.Slf4j;
import org.fintrace.core.drivers.tspl.commands.status.TSPLStatusPollCommands;
import org.fintrace.core.drivers.tspl.connection.EthernetConnectionClient;
import org.fintrace.core.drivers.tspl.connection.USBConnectionClient;
import org.fintrace.core.drivers.tspl.connection.TSPLConnectionClient;
import org.fintrace.core.drivers.tspl.exceptions.ConnectionClientException;
import org.fintrace.core.drivers.tspl.listeners.ClientListener;
import org.fintrace.core.drivers.tspl.listeners.DataListener;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        // USB Client
        TSPLConnectionClient tsplConnectionClient = new USBConnectionClient(
                (short) Integer.parseInt(properties().getProperty("tsc.vendor.id"), 16),
                (short) Integer.parseInt(properties().getProperty("tsc.product.id"), 16));

        tsplConnectionClient.init();

        tsplConnectionClient.connect();

        TscLabel tscLabel = TscLabel.builder()
                .element(Size.builder().labelWidth(4f).labelLength(3f).build())
                .element(Gap.builder().labelDistance(0f).labelOffsetDistance(0f).build())
                .element(Direction.builder().printPositionAsFeed(Boolean.TRUE).build())
                .element(ClearBuffer.builder().build())
                .element(DataMatrix.builder().xCoordinate(10).yCoordinate(110).width(400)
                        .height(400).content("DMATRIX EXAMPLE 1").build())
                .element(DataMatrix.builder().xCoordinate(310).yCoordinate(110).width(400)
                        .height(400).moduleSize(6).content("DMATRIX EXAMPLE 2").build())
                .element(DataMatrix.builder().xCoordinate(10).yCoordinate(310).width(400)
                        .height(400).moduleSize(8).nbRows(18).nbCols(18)
                        .content("DMATRIX EXAMPLE 3").build())
                .element(Print.builder().nbLabels(1).nbCopies(1).build())
                .build();

        tsplConnectionClient.send(tscLabel);

        tsplConnectionClient.disconnect();
        tsplConnectionClient.shutdown();

        System.out.print(tscLabel.getTsplCode());

    }
}`

**Comment by koneru9999** [comment]
Hi @hoangtu92 ,
That properties() is an assumption of the client method in order to get the properties. Sorry if my example is misleading. 

For the USBConnectionClient class, it expects a tsc printer vendor id and tsc printer product id as constructor arguments. You can find these values from the printer's test print.

Hope this helps.

**Comment by hoangtu92** [comment]
Is there any function that I can get these values?
can I get from this printerInfo = PrinterInfo.builder().build();

Sorry I don't have the printer right now to test.

**Comment by hoangtu92** [comment]
@koneru9999 can you help me on this please. Cuz I'm going to make a software to many printers. So I really need to get these value dynamically. Thank you.

**Comment by koneru9999** [comment]
@hoangtu92,

According to TSPL documentation, these vendor id and product id are required In order to establish the connection to the printer.

Im sure these values changes per every printer model atleast.

**Comment by koneru9999** [comment]
@hoangtu92,
Just to understand more, do you intend to write your client software to connect to any product nett dynamically or you just want to connect to one particular printer with support of connecting to different printer models when required ?

**Comment by hoangtu92** [comment]
I need to connect to any product dynamically.

**Comment by hoangtu92** [comment]
So I comeup with usb4java which allow me to get UsbDeviceDescriptor which contain vendorID and productID like this:

`public void test() throws UsbException{

        UsbServices services = UsbHostManager.getUsbServices();
        getPrinterInfo(services.getRootUsbHub(), 0);

    }

    public void getPrinterInfo(UsbDevice device, int level)
    {
        
        for (int i = 0; i < level; i += 1){
            UsbDeviceDescriptor desc = device.getUsbDeviceDescriptor();
            Short vendorID = desc.idVendor();
            Short productID = desc.idProduct();
        }
        if (device.isUsbHub())
        {
            final UsbHub hub = (UsbHub) device;
            for (UsbDevice child: (List<UsbDevice>) hub.getAttachedUsbDevices())
            {
                getPrinterInfo(child, level + 1);
            }
        }

    }`

Hope Vendor ID for all TSC printers be the same.

**Comment by koneru9999** [comment]
@hoangtu92 ,
Awesome!!!


Good to hear that you found a way to obtain these values. Any chance you can contribute to this library with this small util code ?

**Comment by koneru9999** [comment]
@hoangtu92, 
Looking back at your above code snippet, How would you differentiate among different USB devices ?

For example, if there is another usb device like mouse, external hardrive is attached, this code won't be able to guarantee the returned values belong to the TSC printer.

Up to my knowledge, vendor ID has to be the same for all products of same organisation.

refer to http://www.linux-usb.org/usb.ids for list of vendor id.

**Comment by hoangtu92** [comment]
I think so. if all TSC printer have same vendor ID which is should be, then I will just have to compare the vendorID among the USB device list.

I found TSC printer in the list above, very helpful, thanks

1203  TSC Auto ID Technology Co., Ltd
	0140  TTP-245C

**Comment by koneru9999** [comment]
@hoangtu92, 

I will be closing this. 
I've added additionally a single argument constructor to USB connection client so that it will connect only using vendor id.

I would like to still keep this vendor id to be sent by client as the TSPL2 is supported on other printers as well.

Aside to this, 
As this library has been purely developed based on our requirements; Appreciate your valuable suggestions / contributions for this library to improve further in the future.

Thank you.

**Comment by hoangtu92** [comment]
Thanks, I would love to contribute after I finish the work. Since this project intend to use for all TSPL/TSPL2 printer so I think the only way to detect it is send the test command in TSPL language to each USB device, although I do not know if the printer will response or not.
