### ISSUE TITLE
Barcode Rotation

### ISSUE THREAD

**Issue by abailac1** [fintrace/tspl2-driver#18]
Hi, Barcode is not working. 

ShoulD be with rotation 0 but is setting STRING (no_rotation)
BARCODE 380,220, "128",100,0,NO_ROTATION,1,1,0,"123456"
Or null if rotation is not set:
BARCODE 38,220, "128",50,0,null,2,2,1,"LEFT"

**Comment by abailac1** [comment]
should be:

 commandBuilder.append(COMMA)
                .append(EMPTY_SPACE)
                .append(ESCAPED_DOUBLE_QUOTE)
                .append(codeType.getCodeType()).append(ESCAPED_DOUBLE_QUOTE).append(COMMA)
                .append(height).append(COMMA)
                .append(hrcAlignment.getAlignment()).append(COMMA)
                .append(rotation**.getRotation()**).append(COMMA)
                .append(narrow).append(COMMA)
                .append(wide).append(COMMA);

**Comment by koneru9999** [comment]
@abailac1, thanks for the report. 

Indeed it is missing.

**Comment by koneru9999** [comment]
@abailac1 , fix is now available in v0.0.10. 

Thanks for reporting. Closing this particular issue for now.
